import {useT} from '../../i18n/lang';
import {type Pair, W} from '../../i18n/words';
import {PageHeader} from '../../ui/PageHeader';
import u from '../../ui/ui.module.css';


/** Sezioni dei crediti: titolo e paragrafi, ciascuno in italiano e inglese. */
const SECTIONS: { title: Pair; body: Pair[] }[] = [
    {
        title: ['Illustrazioni', 'Illustrations'], body: [
            ['Le illustrazioni delle carte, dei Custodi e degli ambienti sono state generate con strumenti di intelligenza artificiale e selezionate dall\'autore del gioco. In molti ordinamenti le immagini generate interamente da AI non sono tutelate dal diritto d\'autore: altri potrebbero riutilizzarle.',
                'The illustrations of cards, Custodians and environments were generated with artificial intelligence tools and selected by the game\'s author. In many jurisdictions images generated entirely by AI are not protected by copyright: others could reuse them.'],
            ['Le illustrazioni procedurali (stili Dipinta, Vetrata, Incisione) sono generate dal codice del gioco.',
                'The procedural illustrations (Painted, Stained glass and Engraving styles) are generated by the game\'s code.'],
        ]
    },
    {
        title: ['Icone', 'Icons'], body: [
            ['Le figure delle parole chiave e le icone dell\'interfaccia derivano da game-icons.net (autori Lorc, Delapouite e altri), con licenza Creative Commons Attribution 3.0 (CC BY 3.0).',
                'The keyword figures and interface icons are based on game-icons.net (authors Lorc, Delapouite and others), under the Creative Commons Attribution 3.0 licence (CC BY 3.0).'],
        ]
    },
    {
        title: ['Caratteri tipografici', 'Typefaces'], body: [
            ['Grenze Gotisch e Alegreya Sans, distribuiti tramite Google Fonts con licenza SIL Open Font License 1.1.',
                'Grenze Gotisch and Alegreya Sans, distributed through Google Fonts under the SIL Open Font License 1.1.'],
        ]
    },
    {
        title: ['Software', 'Software'], body: [
            ['React, Framer Motion, Zustand e Vite (licenza MIT); d3-delaunay (licenza ISC). Suoni sintetizzati dal gioco con la Web Audio API.',
                'React, Framer Motion, Zustand and Vite (MIT licence); d3-delaunay (ISC licence). Sounds synthesised by the game with the Web Audio API.'],
        ]
    },
    {
        title: ['Storie e ispirazioni', 'Stories and inspirations'], body: [
            ['La lore delle carte si ispira liberamente a miti, leggende e opere di pubblico dominio (mitologia greca e norrena, folclore europeo, Mille e una notte, Shakespeare e altri). I nomi delle fonti sono citati in ogni carta alla voce "Ispirata a".',
                'The card lore is freely inspired by public-domain myths, legends and works (Greek and Norse mythology, European folklore, the Thousand and One Nights, Shakespeare and others). The sources are named on every card under "Inspired by".'],
        ]
    },
    {
        title: ['Marchio', 'Trademark'], body: [
            ['"Rosarcana" è un nome di lavoro. Prima di un uso commerciale va verificata la disponibilità del marchio nei registri pertinenti (per esempio EUIPO e UIBM) e nelle categorie dei videogiochi.',
                '"Rosarcana" is a working title. Before commercial use, trademark availability must be checked in the relevant registers (for example EUIPO and UIBM) and in the video game categories.'],
        ]
    },
    {
        title: ['Acquisti e probabilità', 'Purchases and odds'], body: [
            ['Le gemme in questo prototipo sono simulate e non comportano pagamenti reali. Le probabilità delle bustine e le garanzie sono pubblicate nel negozio.',
                'Gems in this prototype are simulated and involve no real payments. Pack odds and guarantees are published in the shop.'],
        ]
    },
];

/** Crediti, licenze e note legali del prototipo. */
export function Credits({back}: { back: () => void }) {
    const t = useT();
    return (
        <section className={u.page}>
            <PageHeader title={t(W.credits)}
                        sub={t('Rosarcana è un prototipo. Queste informazioni vanno riviste da un professionista prima di una pubblicazione commerciale.', 'Rosarcana is a prototype. This information must be reviewed by a professional before any commercial release.')}>
                <button className={u.btn} onClick={back}>← {t(W.play)}</button>
            </PageHeader>
            {SECTIONS.map(sec => <section key={sec.title[0]} className={u.panel} style={{marginBottom: 14}}>
                <h2 style={{fontSize: 26}}>{t(sec.title)}</h2>
                {sec.body.map(p => <p key={p[0]}>{t(p)}</p>)}
            </section>)}
        </section>
    );
}
