// Le Cronache della Rosa Arcana: lore delle carte, legami tra loro e storie a cui si ispirano.
import type {Faction} from '../engine/types';

export interface Lore {
    text: string;
    flavor: string;
    insp: string;
    links: string[]
}

export const WORLD = {
    title: 'La Rosa Arcana',
    text: [
        "Prima del mondo c'era soltanto la Notte, Nyxa, e nel suo grembo dormivano quattro forze: il fuoco, l'acqua, la radice e il vuoto.",
        "Quando un ladro senza nome rubò alla Notte la prima fiamma e la donò ai mortali, Nyxa si svegliò affamata. Per fermarla, le quattro Casate costruirono la Prima Cattedrale e al suo centro la Rosa Arcana: un rosone di vetro in cui ogni petalo è un Sigillo che tiene la Notte in catene.",
        "Da mille anni le Casate si contendono i Sigilli. Chi ne spezza due, dice la profezia, decide chi custodirà la Rosa nella prossima era. Ma ogni Sigillo che cade allenta una catena, e da qualche parte, in fondo al buio, Nyxa sorride.",
    ],
};

export const FACTION_LORE: Record<Faction, { motto: string; text: string; insp: string }> = {
    brace: {
        motto: 'Il fuoco non si spegne: si passa di mano.', insp: 'Prometeo, la Fenice, Surtr, le Vestali',
        text: "Discendono dal Primo Fuoco, la fiamma rubata alla Notte. Custodiscono le pire che separano i vivi dal buio e vivono all'ombra del Monte, dove dorme il gigante Vulkara. Credono che la luce vada difesa colpendo per primi."
    },
    marea: {
        motto: 'Il mare restituisce sempre qualcosa, ma mai ciò che gli hai dato.',
        insp: "Odissea, Atlantide, Scilla e Cariddi, il Leviatano",
        text: "Eredi di una città sommersa, Atlantide delle Maree. La loro regina Thalassa tenne la Notte lontana dalle coste col suo canto. Non vincono con la forza ma con la pazienza della corrente: spostano, respingono, aspettano."
    },
    radice: {
        motto: 'Ciò che viene tagliato ricresce.', insp: 'Yggdrasil, i Druidi, Persefone, la Lupa capitolina',
        text: "Custodi della foresta che cresce attorno a Yggrin, l'albero le cui radici toccano i tre mondi. Sono lenti e tenaci: ogni ferita si richiude, ogni stagione torna. I loro druidi parlano con i Sigilli come con vecchi amici."
    },
    vuoto: {
        motto: 'Tutto ciò che vive, prima o poi, ci appartiene.',
        insp: "Nyx, Orfeo, Faust, Koschei l'Immortale, Sköll e Hati",
        text: "Servono Nyxa, la Notte incatenata, e lavorano in silenzio per spezzare i Sigilli. Commerciano in anime, patti e ritorni dal regno dei morti. Per loro la morte non è una sconfitta, ma una moneta."
    },
};

const L = (text: string, flavor: string, insp: string, ...links: string[]): Lore => ({text, flavor, insp, links});
export const LORE: Record<string, Lore> = {
    'brace-c0': L("La prima scintilla sfuggita alla torcia del Primo Fuoco. Vaga di focolare in focolare cercando la mano che l'ha liberata.", 'La prima a scappare, la prima ad arrivare.', 'Prometeo', 'brace-l1', 'brace-r0'),
    'brace-c1': L("Allievo della fucina sotto il Monte, batte il ferro al ritmo del cuore di Vulkara. Si dice che abbia forgiato le catene dei Sigilli.", 'Ogni colpo è un battito del Monte.', 'Efesto e Vulcano', 'brace-l0', 'brace-c2'),
    'brace-c2': L("Recluta della Guardia di Cenere. Ha giurato di non lasciar spegnere mai il fuoco che porta sulla schiena, dono del Fabbro di Tizzoni.", 'Ha giurato di non lasciar spegnere mai il suo fuoco.', 'I vigiles di Roma antica', 'brace-c1', 'brace-c4'),
    'brace-c3': L("Il gesto con cui la Capitana dei Roghi accende le pire. Chi lo impara non può più scaldarsi le mani senza bruciare qualcosa.", 'Un gesto solo, e la notte arretra.', 'Il fuoco dal cielo del profeta Elia', 'brace-r2'),
    'brace-c4': L("Custodi del Primo Fuoco, indossano le armature annerite di chi le ha portate prima di loro. Nessuno ricorda il proprio nome: ricordano solo il turno di guardia.", 'Nessuno ricorda il proprio nome, solo il turno di guardia.', 'Le Vestali custodi del fuoco sacro', 'brace-l1', 'brace-c2', 'brace-r2'),
    'brace-c5': L("Portò la fiamma dal Monte alla Cattedrale in una sola notte. Da allora non ha più smesso di correre.", 'Arrivò prima dell\'alba. Non si è più fermato.', 'Fidippide e i tedofori olimpici', 'brace-l1'),
    'brace-u0': L("Forgiato per sfondare le porte di Atlantide delle Maree, tornò indietro fumante e mezzo fuso. I Brace lo considerano comunque una vittoria.", 'Nessuna porta resiste. Quasi nessuna.', 'Il cavallo di Troia e gli arieti d\'assedio', 'marea-u2', 'brace-c1'),
    'brace-u1': L("Quando Vulkara sospira nel sonno, cenere e braci ricadono sui campi per tre giorni.", 'Il Monte sospira, e il cielo brucia.', "L'eruzione che seppellì Pompei", 'brace-l0'),
    'brace-u2': L("Il vessillo della prima rivolta contro la Notte. Non brucia chi lo regge: gli toglie solo la paura.", 'Chi lo regge non trema.', "L'Orifiamma dei re di Francia", 'brace-r2', 'vuoto-l0'),
    'brace-u3': L("Sfida chiunque al tramonto, soprattutto la propria ombra. Finora ha sempre vinto; l'ombra, pazientemente, aspetta.", "Duella al tramonto con la propria ombra.", "L'ombra che fugge nelle fiabe di Andersen", 'vuoto-c1'),
    'brace-r0': L("Figlia della Fenice che arse il giorno della Prima Notte. Ogni volta che rinasce dalle ceneri ricorda un po' meno la madre.", 'Rinasce, e ogni volta dimentica.', 'La Fenice di Erodoto', 'brace-c0', 'brace-l1'),
    'brace-r1': L("La collera di Vulkara che scende dal Monte a sciogliere le mura di chi l'ha offeso.", 'La collera del Monte scende a valle.', 'Pele, dea hawaiana dei vulcani', 'brace-l0', 'brace-u1'),
    'brace-r2': L("Comanda la Guardia di Cenere e tiene accese le pire che separano i vivi dalla Notte. Ha giurato di non dormire finché Nyxa resterà in catene.", 'Non dormirà finché la Notte è in catene.', "Giovanna d'Arco", 'brace-c4', 'brace-c3', 'vuoto-l0'),
    'brace-l0': L("Il gigante di fuoco nato quando il Primo Fuoco toccò la terra. Dorme sotto il Monte e, dicono, si sveglierà per bruciare il mondo alla fine dei tempi.", 'Dorme. Per ora.', 'Surtr, il gigante di fuoco del mito norreno', 'brace-l1', 'radice-l0', 'brace-c1'),
    'brace-l1': L("La fiamma rubata alla Notte da un ladro senza nome e consegnata ai mortali. Tutte le Brace discendono da lei, e tutte le guerre dei Sigilli cominciano da lei.", 'Da lei discende ogni luce.', 'Prometeo che ruba il fuoco agli dèi', 'brace-c0', 'vuoto-l0', 'brace-r0'),

    'marea-c0': L("Uno scherzo delle nereidi: rimanda a riva ciò che il mare non vuole.", 'Il mare rifiuta ciò che non gli piace.', 'Le Nereidi', 'marea-l0'),
    'marea-c1': L("Getta la rete nella nebbia e pesca ricordi di marinai perduti. Una volta tirò su un'anfora sigillata: la ributtò in acqua senza aprirla, e fu la cosa più saggia della sua vita.", 'Pesca ricordi nella nebbia, e ne ributta qualcuno.', 'Il pescatore e il genio, dalle Mille e una notte', 'marea-u0', 'vuoto-r2'),
    'marea-c2': L("Le anguille della baia nuotano fino a un mare lontano per nascere e morire. Nessuno le ha mai viste tornare, eppure tornano sempre.", 'Nessuno le ha mai viste tornare.', 'Il mistero delle anguille e del Mar dei Sargassi', 'marea-r0'),
    'marea-c3': L("Soldati annegati durante la caduta di Atlantide, lentamente trasformati in corallo. Sorvegliano ancora porte che nessuno apre più.", 'Sorvegliano porte che nessuno apre più.', 'Atlantide nel racconto di Platone', 'marea-u2', 'marea-u3'),
    'marea-c4': L("La risacca porta via e restituisce. I vecchi marinai dicono che conta ogni sasso, per sapere se è stato un buon giorno.", 'Porta via, restituisce, conta.', 'I canti dei marinai', 'marea-l1'),
    'marea-c5': L("Chi la guarda troppo a lungo si ferma come pietra, anche solo per un istante. È tutto ciò che resta di un antico sguardo di Gorgone.", 'Uno sguardo, e il tempo si ferma.', 'Medusa e le Gorgoni', 'marea-l0'),
    'marea-u0': L("Legge il futuro nelle perle ma parla solo per enigmi. Ha predetto tre volte il ritorno di Nyxa, e tre volte nessuno le ha creduto.", 'Dice sempre il vero. Nessuno le crede mai.', 'Cassandra e il vecchio del mare Proteo', 'vuoto-l0', 'marea-l0'),
    'marea-u1': L("La maledizione di chi offese il mare: ogni volta che la riva è vicina, la corrente lo riporta al largo.", 'La riva è sempre un po\' più lontana.', "Odisseo perseguitato da Poseidone", 'marea-r2'),
    'marea-u2': L("L'ultimo faro di Atlantide brilla ancora sotto le onde e guida navi che non esistono più.", 'Guida navi che non esistono più.', "Il Faro di Alessandria e Atlantide", 'marea-c3', 'brace-u0'),
    'marea-u3': L("Una tartaruga così antica che sul suo guscio è cresciuta un'isola. Dei monaci ci sbarcarono per dire messa, credendola terra.", 'Sulla sua schiena qualcuno ha costruito una chiesa.', "San Brandano e l'isola che si muoveva", 'marea-r1', 'radice-l0'),
    'marea-r0': L("Il gorgo tra le due scogliere. Chi passa troppo vicino a una incontra il mostro, chi troppo vicino all'altra il vortice.", 'Tra il mostro e il vortice.', 'Scilla e Cariddi', 'marea-r1', 'marea-c2'),
    'marea-r1': L("Ancora cucciola, è già più grande di una flotta. Sua madre dorme sul fondo dell'oceano, avvolta attorno alle radici del mondo.", 'Ancora cucciola, già più grande di una flotta.', 'Il Leviatano e il serpente del mondo Jörmungandr', 'radice-l0', 'marea-r0'),
    'marea-r2': L("Ha navigato dieci anni per tornare a casa e ha smesso di contarli. Le sue navi obbediscono al vento prima ancora che lui parli.", 'Dieci anni per tornare a casa. Ci arriverà.', "Odisseo", 'marea-u1', 'marea-l0'),
    'marea-l0': L("Regina del mare più antico, canta per i naufraghi e li chiama a sé. Il suo canto tenne Nyxa lontana dalle coste per mille anni.", 'Il suo canto tiene lontana la Notte.', 'Le Sirene e Thalassa, lo spirito del mare', 'marea-r2', 'vuoto-l0', 'marea-c5'),
    'marea-l1': L("Il diluvio che lavò il mondo dopo la Prima Notte. Si dice che tornerà quando l'ultimo Sigillo si spezzerà.", "Tornerà quando cadrà l'ultimo Sigillo.", 'Il Diluvio di Gilgamesh e di Noè', 'marea-l0', 'vuoto-l1'),

    'radice-c0': L("Spunta dalle crepe del selciato della Cattedrale. I custodi lo strappano ogni mattina; ogni sera è di nuovo lì.", 'Lo strappano ogni mattina. Ogni sera è lì.', 'La fiaba del seme ostinato', 'radice-l1', 'radice-u1'),
    'radice-c1': L("Ha dormito così a lungo nella foresta che il muschio lo ha scambiato per una roccia. Ora parla con i Sigilli come con vecchi amici.", 'Parla con i Sigilli come con vecchi amici.', 'I Druidi celtici e Merlino', 'radice-u2', 'radice-l1'),
    'radice-c2': L("Discendente del cinghiale che nessun cacciatore riuscì mai ad abbattere. Dove passa, il rovo ricresce più fitto.", 'Dove passa, il rovo ricresce più fitto.', 'Il cinghiale di Calidone', 'radice-c4'),
    'radice-c3': L("La benedizione della Quercia: una pelle di corteccia che resiste alla lama quanto al tempo.", 'Resiste alla lama quanto al tempo.', 'Dafne trasformata in alloro', 'radice-u0'),
    'radice-c4': L("Caccia nei boschi da prima che esistessero i nomi. Non ha mai mancato un bersaglio, tranne un cinghiale di rovo che insegue ancora.", 'Non ha mai mancato un bersaglio. Tranne uno.', 'Artemide cacciatrice e Robin Hood', 'radice-c2', 'radice-r2'),
    'radice-c5': L("Una goccia della rugiada che cade da Yggrin. Chi la beve ricorda di essere vivo.", 'Chi la beve ricorda di essere vivo.', "La rugiada dell'albero del mondo nell'Edda", 'radice-l0'),
    'radice-u0': L("Le querce sacre ascoltavano le domande dei pellegrini. Questa, stanca di ascoltare, ha cominciato a rispondere.", 'Stanca di ascoltare, ha cominciato a rispondere.', "Le querce parlanti dell'oracolo di Dodona", 'radice-c3', 'radice-c1'),
    'radice-u1': L("I funghi sono la memoria sotterranea della foresta: ogni spora porta un ricordo a un albero lontano.", 'Ogni spora porta un ricordo.', 'I cerchi delle fate', 'radice-c0'),
    'radice-u2': L("Nessuno sa chi abbia innalzato le pietre, ma tutti sanno che non vanno contate: il numero cambia ogni volta.", 'Non contarle. Il numero cambia.', 'Stonehenge e le pietre che non si lasciano contare', 'radice-c1'),
    'radice-u3': L("Allattò due gemelli abbandonati sulla riva di un fiume, che poi fondarono una città. I suoi fratelli selvaggi inseguono ancora il sole e la luna nel cielo.", 'Protegge chi non ha nessuno.', 'La Lupa capitolina di Romolo e Remo', 'vuoto-r0', 'radice-r2'),
    'radice-r0': L("Avvolse per cento anni la torre di una principessa addormentata. Quando lei se ne andò, il rampicante rimase ad aspettare.", 'Cent\'anni ad aspettare. Può aspettarne altri cento.', 'La bella addormentata', 'radice-l1'),
    'radice-r1': L("Ogni primavera la figlia della Terra risale dagli inferi, e i campi rinascono al suo passaggio.", 'Ogni primavera, lei ritorna.', 'Persefone e Demetra', 'vuoto-u1', 'radice-l1'),
    'radice-r2': L("Una cacciatrice trasformata in orsa e poi portata tra le stelle. Scende sulla terra solo per proteggere i suoi cuccioli.", 'Scende dalle stelle per i suoi cuccioli.', "Callisto e l'Orsa Maggiore", 'radice-c4', 'radice-u3'),
    'radice-l0': L("Le sue radici toccano i tre mondi: la terra dei vivi, il fondo del mare e il pozzo della Notte. Quando cammina, il mondo intero scricchiola.", 'Quando cammina, il mondo scricchiola.', "Yggdrasil, l'albero del mondo norreno", 'marea-r1', 'vuoto-c4', 'brace-l0', 'radice-l1'),
    'radice-l1': L("Il seme da cui germogliò Yggrin. Il Druida di Muschio lo custodisce per piantarlo all'inizio della prossima era.", 'Il mondo di domani, in un pugno.', "L'uovo cosmico e il seme del mondo", 'radice-l0', 'radice-c1'),

    'vuoto-c0': L("Ha consegnato il proprio nome alla Notte in cambio di una candela che non si spegne mai. La sua luce è nera.", 'Ha dato il suo nome per una candela nera.', 'I culti misterici', 'vuoto-l0', 'vuoto-c2'),
    'vuoto-c1': L("Un'ombra fuggita al suo padrone che ora cerca un corpo da imitare. Ha fame di forma, di peso, di passi.", 'Un\'ombra fuggita al padrone, affamata di forma.', "L'ombra di Andersen e quella di Peter Pan", 'brace-u3'),
    'vuoto-c2': L("Un contratto firmato col sangue: anni di sapere in cambio di un'anima. Nessuno ha mai letto tutte le clausole.", 'Nessuno ha mai letto tutte le clausole.', 'Il patto di Faust', 'vuoto-c0', 'vuoto-u3'),
    'vuoto-c3': L("Uscendo dagli inferi si voltò a guardare indietro, e perse ciò che amava. Ora vaga avanti e indietro senza trovare pace.", 'Si voltò una volta sola. Bastò.', 'Orfeo ed Euridice', 'vuoto-u1'),
    'vuoto-c4': L("Un occhio lasciato in pegno in fondo al pozzo sotto le radici di Yggrin, in cambio della saggezza. Vede tutto, tranne chi l'ha donato.", 'Vede tutto, tranne chi l\'ha donato.', 'Odino e il pozzo di Mímir', 'radice-l0'),
    'vuoto-c5': L("La voce che parlò per prima al cuore di un re geloso. Basta una parola nell'orecchio giusto per disarmare un esercito.", 'Una parola, nell\'orecchio giusto.', "Iago nell'Otello di Shakespeare", 'vuoto-r2'),
    'vuoto-u0': L("Raccoglie ciò che resta sul campo dopo ogni battaglia. Non ha fretta: tutto, prima o poi, matura.", 'Non ha fretta. Tutto matura.', 'La Morrígan e il Tristo Mietitore', 'vuoto-l0'),
    'vuoto-u1': L("Il canto che convinse la regina degli inferi a restituire un'anima. Funziona sempre, a patto di non voltarsi.", 'Funziona sempre, se non ti volti.', 'Orfeo ed Euridice', 'vuoto-c3', 'radice-r1'),
    'vuoto-u2': L("Sull'altare della Prima Notte fu versato il primo sangue. La crepa si allarga ogni volta che qualcuno ci si inginocchia.", 'La crepa si allarga a ogni preghiera.', 'Il sacrificio di Ifigenia', 'vuoto-c2'),
    'vuoto-u3': L("Ha rubato l'anima del Sovrano Cavo e l'ha nascosta in un ago, dentro un uovo, dentro un'anatra, dentro un forziere.", 'Un ago, in un uovo, in un\'anatra, in un forziere.', "Koschei l'Immortale", 'vuoto-r2'),
    'vuoto-r0': L("Il lupo della Notte che insegue le stelle. Ne ha già divorate abbastanza da oscurare metà del cielo; la sorella lupa, sulla terra, non lo ha mai perdonato.", 'Ha già divorato metà del cielo.', 'I lupi Sköll e Hati del mito norreno', 'vuoto-r1', 'radice-u3'),
    'vuoto-r1': L("Il giorno in cui il lupo raggiunse il sole. Durò pochi minuti, ma nessuno di quelli che lo videro dormì più tranquillo.", 'Il giorno in cui il lupo raggiunse il sole.', 'Sköll che divora il sole', 'vuoto-r0', 'brace-l1'),
    'vuoto-r2': L("Un re che nascose la propria anima per non morire mai. Ci è riuscito: ora non vive nemmeno.", 'Non morirà mai. Non vive nemmeno.', "Koschei l'Immortale", 'vuoto-u3', 'marea-c1'),
    'vuoto-l0': L("La Notte che c'era prima del mondo. Fu incatenata dai Sigilli della Rosa Arcana, ma ogni Sigillo spezzato allenta una catena.", 'Ogni Sigillo spezzato allenta una catena.', 'Nyx, la Notte primordiale di Esiodo', 'brace-l1', 'marea-l0', 'radice-l0', 'vuoto-l1'),
    'vuoto-l1': L("Ciò che resterà quando l'ultimo Sigillo cadrà: niente grida, niente canti, niente vento.", 'Niente grida. Niente canti. Niente vento.', 'Il Ragnarök e il grande inverno Fimbulvetr', 'vuoto-l0', 'marea-l1'),

    'brace-c6': L('Grifoni nati nella cenere del Monte: le loro piume non smettono mai di fumare.', 'Le sue piume fumano ancora.', 'Il grifone delle leggende medievali', 'brace-l0'),
    'brace-u4': L("Accende le micce sotto le mura nemiche e sparisce prima dell'esplosione. Nessuno ha mai visto il suo volto.", 'Una miccia, e poi il silenzio.', "I sabotatori delle guerre d'assedio", 'brace-u0'),
    'brace-r3': L('Il più anziano dei Guardiani della Fornace. Dove cammina, le braci si rianimano e i soldati trovano coraggio.', 'Dove passa, le braci si rianimano.', 'Loki e il fuoco che ispira i guerrieri', 'brace-c4', 'brace-r2'),
    'marea-c6': L('Segue le navi fino alle secche e grida quando il fondale si avvicina. I marinai lo considerano un buon presagio.', 'Grida quando il fondale si avvicina.', 'Il gabbiano dei marinai', 'marea-r2'),
    'marea-u4': L('Quando la marea sale, ogni passo costa il doppio. I Maree la invocano per rallentare chi li insegue.', 'Ogni passo costa il doppio.', 'Il re Canuto e la marea che non obbedisce', 'marea-l1'),
    'marea-r3': L('Canta per chi la ascolta e il nemico dimentica di combattere. Thalassa le ha insegnato una sola canzone.', 'Una sola canzone, e il nemico dimentica.', 'Le Sirene di Ulisse', 'marea-l0'),
    'radice-c6': L('Veglia sulle sorgenti dove nasce la linfa di Yggrin. Chi beve lì sente crescere la propria forza.', 'Dove beve, la forza cresce.', 'Le ninfe delle sorgenti', 'radice-l0', 'radice-c5'),
    'radice-u4': L('Piccola, lenta e paziente. Un solo morso basta anche per il più grande dei cinghiali.', 'Un morso basta.', "L'aspide di Cleopatra", 'radice-c2'),
    'radice-r3': L('Chi lo vede nel bosco trova la strada di casa. Chi lo caccia non trova più nulla.', 'Chi lo vede trova la strada di casa.', 'Il cervo bianco delle leggende arturiane', 'radice-c4'),
    'vuoto-c6': L('Copia ogni incantesimo che ascolta sulle pareti della cripta. La sua biblioteca non ha porte.', 'Una biblioteca senza porte.', 'Gli scriptoria e i libri proibiti', 'vuoto-c4'),
    'vuoto-u4': L('Dorme appeso alle volte della cripta e si sveglia solo quando sente il sangue.', 'Si sveglia al profumo del sangue.', 'I pipistrelli delle cripte e i vampiri', 'vuoto-u2'),
    'vuoto-r3': L('Quando il lupo copre il sole per intero, le cose deboli smettono di esistere.', 'Le cose deboli smettono di esistere.', 'Il Fimbulvetr e il sole divorato', 'vuoto-r1', 'vuoto-r0'),
    'brace-c7': L('Batte il tempo della marcia con due ossa annerite. Chi la sente non riesce a restare indietro.', 'Chi la sente non resta indietro.', 'I tamburini delle legioni'),
    'brace-c8': L('Una scheggia della Fornace, lanciata da chi sa dove fa più male.', 'Piccola, ma trova sempre la crepa.', 'Le frecce incendiarie degli assedi'),
    'brace-c9': L('Ha giurato di bruciare prima che il fuoco si spenga. Paga con la propria pelle ciò che non può pagare in oro.', 'Paga con la pelle ciò che non ha in oro.', 'I flagellanti medievali'),
    'brace-c10': L('Resta immobile sulle mura, avvolta nel fumo. Si muove solo quando il suo Sigillo cade.', 'Si muove solo quando tutto crolla.', 'Le sentinelle di Pompei rimaste al loro posto'),
    'brace-u5': L('Nelle ceneri del campo di battaglia trova la sua furia. Più brucia, più combatte.', 'Più brucia, più combatte.', 'I berserkir norreni'),
    'brace-u6': L('Una pira accesa ogni sera sulle mura. Il fumo cerca il nemico più debole e lo soffoca.', 'Il fumo trova sempre il più debole.', 'I fuochi votivi dei templi antichi'),
    'brace-u7': L('Ha combattuto sotto ogni cielo, e ogni presagio gli ricorda una vittoria.', 'Ogni cielo gli ricorda una vittoria.', 'I veterani delle guerre puniche'),
    'brace-r4': L('Nato nel cuore del Monte, vola sopra le mura e piove fuoco su chi le difende.', 'Dove passa, le mura non servono più.', 'Fáfnir e i draghi delle saghe'),
    'brace-r5': L('Quando Vulkara perde la pazienza, una corsia intera diventa lava.', 'Una corsia intera diventa lava.', 'Il Vesuvio del 79 d.C.'),
    'brace-r6': L('Porta lo stendardo e il grido di guerra. Dove arriva, ogni Guardiano ritrova il fuoco.', 'Dove arriva, il fuoco si rialza.', 'Gli araldi dei tornei medievali'),
    'brace-l2': L('Il gigante che, nelle leggende, porterà il fuoco alla fine del mondo. Nella Rosa, lo porta adesso.', 'Il fuoco della fine, portato adesso.', 'Surtr del Ragnarök'),
    'brace-l3': L('La fornace che non si spegne mai. Chi lavora accanto a lei fa tutto più in fretta.', 'Chi lavora accanto a lei non si stanca.', 'La fucina di Efesto'),
    'marea-c7': L('Sale dal nulla, spazza via chi non è ben piantato e torna al mare come se niente fosse.', 'Sale dal nulla, torna al nulla.', 'Le onde anomale dei marinai'),
    'marea-c8': L('Chiude le chele davanti ai compagni e aspetta. Nessuno è mai riuscito ad aprirle.', 'Nessuno ha mai aperto le sue chele.', "Il granchio di Eracle nell'Idra"),
    'marea-c9': L('Si immerge solo quando il cielo manda un segno. Allora torna sempre con qualcosa.', 'Si immerge solo quando il cielo parla.', 'I pescatori di perle del Golfo'),
    'marea-c10': L('Una nebbia che sa di sale e fa dimenticare dove si stava andando.', 'Fa dimenticare dove si andava.', 'Le nebbie di Avalon'),
    'marea-u5': L('Esplora le correnti laterali e sbuca dove nessuno lo aspetta.', 'Sbuca sempre dove non lo aspetti.', 'Tritone, messaggero del mare'),
    'marea-u6': L("L'ancora di una nave affondata. Ancora oggi trattiene chi le passa accanto.", 'Trattiene ancora chi le passa accanto.', "L'ancora della nave di Teseo"),
    'marea-u7': L('Legge le correnti come un libro. Quando un Sigillo cade, sa già cosa verrà dopo.', 'Sa già cosa verrà dopo.', 'Circe e le maghe del mare'),
    'marea-r4': L('Dorme sul fondo da mille anni. Quando si sveglia, il mare intero trattiene il respiro.', 'Il mare trattiene il respiro.', 'Il Kraken delle leggende scandinave'),
    'marea-r5': L('La marea che torna indietro nel momento peggiore, lasciando il nemico a mani vuote.', 'Torna indietro nel momento peggiore.', 'Il passaggio del Mar Rosso'),
    'marea-r6': L('Regna sulle secche dove le navi si arenano. Chi la serve non affonda mai.', 'Chi la serve non affonda.', 'Anfitrite, regina del mare'),
    'marea-l2': L('Il mostro dello stretto: sei teste, dodici braccia e nessuna pietà per chi passa troppo vicino.', 'Nessuna pietà per chi passa vicino.', "Scilla dell'Odissea"),
    'marea-l3': L('La meraviglia del mondo antico, rinata nella Rosa. La sua luce mostra ogni giorno una via nuova.', 'Ogni giorno una via nuova.', 'Il Faro di Alessandria'),
    'radice-c7': L('Cresce lentamente sulle pietre dei Sigilli e non si stacca più.', 'Lento, ma non si stacca più.', 'Il muschio sulle pietre di Stonehenge'),
    'radice-c8': L('Un seme portato dal vento. Dove cade, la terra si fa più generosa.', 'Dove cade, la terra dona.', 'La parabola del seminatore'),
    'radice-c9': L('Ancora giovane, ma sente i presagi prima dei lupi adulti.', 'Sente il presagio prima degli altri.', 'I lupi di Gubbio'),
    'radice-c10': L('Raccoglie erbe ai piedi dei Sigilli e con quelle ne cura le crepe.', 'Cura le crepe con le erbe.', 'Ildegarda di Bingen'),
    'radice-u5': L('Un albero che si è messo a camminare per difendere il bosco. Ciò che lo ferisce lo nutre.', 'Ciò che lo ferisce lo nutre.', 'Gli Ent e gli alberi guardiani'),
    'radice-u6': L('Un anello di funghi che si allarga ogni notte. Chi ci entra non esce da solo.', 'Chi ci entra non esce da solo.', 'I cerchi delle fate del folklore irlandese'),
    'radice-u7': L('Carica quando tutto sembra perduto. La rabbia lo rende più grande.', 'La rabbia lo fa più grande.', 'Il cinghiale calidonio'),
    'radice-r4': L('Vive da prima dei Sigilli. Quando parla, la foresta cresce e le crepe si richiudono.', 'Quando parla, la foresta cresce.', 'Le driadi della mitologia greca'),
    'radice-r5': L('Il corno dei guardiani risuona tra gli alberi, e ogni creatura del bosco risponde.', 'Ogni creatura del bosco risponde.', 'Il corno di Orlando'),
    'radice-r6': L('Guida i branchi del bosco. Ogni ferita che i suoi infliggono torna come linfa alla terra.', 'Ogni ferita torna alla terra.', 'Cernunno, il dio cervo'),
    'radice-l2': L('La quercia più vecchia del mondo si è alzata. Nessuno la sposta, nessuno la passa.', 'Nessuno la sposta, nessuno la passa.', 'La quercia di Dodona'),
    'radice-l3': L('La primavera che non finisce mai. Ogni ferita si chiude, ogni Sigillo respira.', 'Ogni ferita si chiude.', 'Persefone e il ritorno della primavera'),
    'vuoto-c7': L("Ha appena preso i voti. Il suo primo sacrificio sarà anche l'ultimo.", "Il primo sacrificio è l'ultimo.", 'Le novizie dei monasteri'),
    'vuoto-c8': L('Si offre qualcosa al Vuoto, e il Vuoto restituisce forza. Il conto arriva sempre.', 'Il conto arriva sempre.', 'I tributi agli dèi degli inferi'),
    'vuoto-c9': L('Le ossa si ricompongono ogni volta. Non ricordano perché combattono, ma non smettono.', 'Le ossa si ricompongono sempre.', 'Gli scheletri degli Argonauti'),
    'vuoto-c10': L('Un sussurro che sale dal pozzo e porta ciò che cerchi. A volte troppo in fretta.', 'Porta ciò che cerchi.', 'Il pozzo di Mímir'),
    'vuoto-u5': L('Chiama i morti più piccoli, quelli che nessuno piange, e li rimette in piedi.', 'Rialza chi nessuno piange.', 'La negromanzia medievale'),
    'vuoto-u6': L('Custodisce ossa di santi e di dannati. Ogni morte vicino a lui gli sussurra un segreto.', 'Ogni morte gli sussurra un segreto.', 'I reliquiari delle cattedrali gotiche'),
    'vuoto-u7': L('Prega nel silenzio e aspetta. Quando un Sigillo si spezza, le sue preghiere hanno risposta.', 'Le sue preghiere hanno risposta.', 'Le sacerdotesse di Ecate'),
    'vuoto-r4': L('Si nutre delle anime dei compagni. Ogni anima lo rende più grande e più vuoto.', 'Più grande, e più vuoto.', 'I divoratori di anime delle leggende egizie'),
    'vuoto-r5': L("Un patto firmato nell'ombra: il nemico cade, ma anche la tua casa trema.", 'Il nemico cade, e la tua casa trema.', 'Il patto di Faust'),
    'vuoto-r6': L('Guida la liturgia del silenzio. I suoi fedeli, anche morti, tornano sempre a pregare.', 'Anche morti, tornano a pregare.', 'Gli inquisitori e i riti di morte'),
    'vuoto-l2': L('La regina del regno dei morti apre le porte, e i suoi sudditi tornano a combattere.', 'Apre le porte, e i morti tornano.', 'Hel della mitologia norrena'),
    'vuoto-l3': L('Il patto più antico: una vita ogni alba, in cambio del fuoco sui Sigilli nemici.', 'Una vita ogni alba.', 'I sacrifici agli dèi del sole'),
    'tok-germoglio': L("Nato da una spora, non sa ancora cosa diventerà.", 'Non sa ancora cosa diventerà.', 'I cerchi delle fate', 'radice-u1'),
    'tok-cucciolo': L("Segue la madre ovunque, anche in battaglia.", 'Segue la madre ovunque.', "Callisto e l'Orsa Minore", 'radice-r2'),
};
export const loreOf = (id: string): Lore | undefined => LORE[id];
