// Frammenti nascosti del Codex: si sbloccano portando la carta al grado di maestria Adepto.
export const SECRETS: Record<string, string> = {
  'brace-c0': "La mano che l'ha liberata era di una bambina: oggi è la Capitana dei Roghi, e non se lo ricorda.",
  'brace-c1': 'Una delle catene dei Sigilli ha un anello difettoso. Il Fabbro lo sa, e non l\'ha mai detto a nessuno.',
  'brace-c2': 'Il suo lanciafiamme brucia il combustibile dei ricordi: ogni fiammata gli toglie un giorno d\'infanzia.',
  'brace-c3': 'Il gesto nacque per accendere candele. Diventò un\'arma la notte in cui la prima Vestale fu tradita.',
  'brace-c4': 'Le armature annerite sono sempre le stesse cento. Quando una Guardia muore, la prossima eredita il suo turno di guardia a metà.',
  'brace-c5': 'Non corre verso la Cattedrale: corre via da qualcosa che lo inseguiva quella notte, e che non ha mai smesso.',
  'brace-u0': 'La testa di montone è un calco: sotto c\'è il volto di un re di Atlantide, fuso nel bronzo per sfregio.',
  'brace-u1': 'La cenere di Vulkara, sparsa sui campi, li rende i più fertili del regno. Il Monte dà e toglie nello stesso respiro.',
  'brace-u2': 'Lo Stendardo è cucito con i mantelli dei primi caduti. Chi lo regge sente i loro nomi sussurrati nel vento.',
  'brace-u3': 'La sua ombra non vuole vincere: vuole solo che lui smetta di sfidarla, per potersene andare.',
  'brace-r0': 'La madre non è morta del tutto: brucia ancora, piccola, nel cuore della Fornace, in attesa di una figlia che si ricordi.',
  'brace-r1': 'La collera di Vulkara ha una direzione precisa: verso il luogo dove fu seppellito il ladro senza nome.',
  'brace-r2': 'Dorme, in realtà. Solo di giorno, e solo per pochi minuti, mentre le Guardie fingono di non accorgersene.',
  'brace-l0': 'Vulkara non vuole bruciare il mondo: vuole riscaldarlo abbastanza perché Nyxa non torni mai.',
  'brace-l1': 'Il ladro senza nome è ancora vivo. Custodisce il Primo Fuoco da dentro, come la sua ultima scintilla.',
  'marea-c0': 'Le nereidi non scherzano mai davvero: ogni cosa che respingono a riva è un avvertimento.',
  'marea-c1': 'L\'anfora che ributtò in mare conteneva un genio. Ora quel genio aspetta il pescatore successivo, meno saggio.',
  'marea-c2': 'Le anguille nascono tutte nello stesso punto: sopra la tomba di Atlantide, dove il mare è più caldo.',
  'marea-c3': 'Il corallo cresce sui soldati da mille anni, ma dentro le armature batte ancora un cuore lentissimo.',
  'marea-c4': 'I sassi che la risacca conta non sono sassi: sono i denti dei marinai che hanno sfidato Thalassa.',
  'marea-c5': 'La Medusa non trasforma in pietra. Mostra a chi la guarda il momento della propria morte, e il corpo si ferma per lo spavento.',
  'marea-u0': 'La Veggente ha visto anche la propria fine: morirà il giorno in cui qualcuno le crederà.',
  'marea-u1': 'La Corrente non odia i naviganti: li protegge da una riva che non esiste più.',
  'marea-u2': 'La luce del Faro è alimentata dall\'ultimo respiro dei naufraghi. Per questo non si spegne mai.',
  'marea-u3': 'La tartaruga ricorda la chiesa costruita sul suo guscio. Ogni tanto, la notte, canta ancora le sue preghiere.',
  'marea-r0': 'Il mostro e il vortice sono la stessa creatura: due bocche dello stesso mare affamato.',
  'marea-r1': 'La madre della Leviatana tiene insieme le radici del mondo. Se si svegliasse, Yggrin cadrebbe.',
  'marea-r2': 'L\'Ammiraglio è già arrivato a casa, anni fa. Ha trovato tutto cambiato, ed è ripartito senza dirlo a nessuno.',
  'marea-l0': 'Thalassa non canta per attirare i naufraghi: canta per coprire un\'altra voce, quella di Nyxa, che sale dal fondo.',
  'marea-l1': 'Il diluvio non fu una punizione: fu il mare che provò a spegnere il Primo Fuoco. Non ci riuscì del tutto.',
  'radice-c0': 'Il germoglio non ricresce per ostinazione: sotto il selciato c\'è una radice di Yggrin che non vuole essere dimenticata.',
  'radice-c1': 'Il Druida non dorme davvero: ascolta. I Sigilli gli raccontano ogni notte quanto manca.',
  'radice-c2': 'Il Cinghiale non fugge dall\'Arciera: la guida lontano da un sentiero che nessuno deve trovare.',
  'radice-c3': 'La benedizione della Quercia ha un prezzo: chi la porta troppo a lungo comincia a mettere radici.',
  'radice-c4': 'L\'unico bersaglio mancato fu voluto. Il Cinghiale era suo fratello, trasformato da una maledizione.',
  'radice-c5': 'Una goccia fa ricordare di essere vivi. Due fanno ricordare tutte le vite precedenti. Nessuno ne beve tre.',
  'radice-u0': 'La Quercia risponde solo a domande sincere. Alle altre risponde con la verità, che è peggio.',
  'radice-u1': 'Le spore portano ricordi, ma anche bugie: la foresta non è sempre d\'accordo con se stessa.',
  'radice-u2': 'Le pietre cambiano numero perché una di loro cammina, di notte, e non sempre torna al suo posto.',
  'radice-u3': 'La Lupa ha allattato anche un terzo gemello, dimenticato dalla storia. Ora vive nel Vuoto, e porta un altro nome.',
  'radice-r0': 'La principessa non si svegliò per un bacio: fu il Rampicante a lasciarla andare, perché lei glielo chiese in sogno.',
  'radice-r1': 'Ogni primavera la figlia della Terra porta con sé qualcosa dagli inferi. Quest\'anno, un seme nero.',
  'radice-r2': 'Scende dalle stelle solo per i cuccioli, ma una volta scese per un uomo: il cacciatore che l\'aveva trasformata.',
  'radice-l0': 'Yggrin cammina perché una delle sue radici è stata spezzata nel pozzo della Notte, e cerca di tornare intera.',
  'radice-l1': 'Il Seme del Mondo è vuoto. Il Druida lo sa: il mondo nuovo dovrà nascere da chi lo pianterà.',
  'vuoto-c0': 'Il nome dell\'Accolito è scritto sulla candela. Se qualcuno lo leggesse ad alta voce, sarebbe libero.',
  'vuoto-c1': 'L\'Ombra imita il Duellante di Brace da così tanto tempo che ormai è lui a imitare lei.',
  'vuoto-c2': 'L\'ultima clausola del Patto dice che l\'anima torna indietro se il firmatario ride davvero una volta. Nessuno ci è riuscito.',
  'vuoto-c3': 'Lo Spettro non si voltò per dubbio: si voltò perché lei lo chiamò. E lei lo sa.',
  'vuoto-c4': 'Odino vide attraverso l\'Occhio la fine del mondo. L\'Occhio, attraverso Odino, vide qualcosa di peggio.',
  'vuoto-c5': 'Il Sussurro ha parlato anche a Nyxa, prima del mondo. È stato lui a dirle che la luce era un furto.',
  'vuoto-u0': 'La Mietitrice lascia sempre qualcosa sul campo: un solo seme, per ogni vita raccolta.',
  'vuoto-u1': 'Il canto funziona sempre. Il problema è che chi torna non è mai esattamente chi era partito.',
  'vuoto-u2': 'Il primo sangue versato sull\'Altare era della Notte stessa. Per questo la crepa non smette di crescere.',
  'vuoto-u3': 'Il Ladro d\'Anime ha nascosto anche la propria anima, per sicurezza. Ha dimenticato dove.',
  'vuoto-r0': 'Il Divoratore non mangia le stelle per fame: ognuna è un Sigillo di un mondo precedente.',
  'vuoto-r1': 'Durante l\'Eclissi, per pochi minuti, i Sigilli della Rosa smettono di funzionare. Nyxa conta ogni secondo.',
  'vuoto-r2': 'Il Sovrano Cavo cerca ancora l\'ago con la sua anima. Non sa che il Pescatore di Nebbie l\'ha ripescato.',
  'vuoto-l0': 'Nyxa non odia il mondo. È gelosa della luce che le fu rubata, perché era l\'unica cosa che aveva mai visto.',
  'vuoto-l1': 'Il Silenzio è già stato, una volta. Tutto ciò che esiste è quello che è sopravvissuto alla sua prima fine.',
  'brace-c6': 'I grifoni di cenere nascono dove un Guardiano muore, dalla sua ultima brace.',
  'brace-u4': 'È la sorella minore della Capitana dei Roghi, e ha scelto la strada opposta.',
  'brace-r3': "Porta al collo l'ultima scintilla sfuggita al Primo Fuoco dopo la Scintilla Errante.",
  'marea-c6': 'I gabbiani sono le anime dei marinai di Atlantide che non hanno voluto riposare.',
  'marea-u4': "L'Alta Marea non è una magia: è Thalassa che respira più forte.",
  'marea-r3': "La sua unica canzone è l'ultima strofa di quella che teneva lontana Nyxa.",
  'radice-c6': 'Le sorgenti che custodisce sono le lacrime di Yggrin per la radice spezzata.',
  'radice-u4': "La Vipera è l'unico animale che l'Orsa Madre teme.",
  'radice-r3': "Il Cervo Bianco è l'ultimo sogno del Seme del Mondo prima di germogliare.",
  'vuoto-c6': "La biblioteca dello Scriba contiene una sola pagina bianca: il nome dell'Accolito.",
  'vuoto-u4': 'I pipistrelli portano a Nyxa le notizie di ciò che accade sotto i Sigilli.',
  'vuoto-r3': "La Grande Eclisse è già accaduta una volta, e nessuno ricorda cosa c'era prima.",
  'brace-c7': 'Il suo tamburo è fatto con la pelle di una salamandra di Vulkara, e batte da solo quando lei dorme.',
  'brace-c8': 'Ogni scheggia ricorda il punto esatto del Sigillo da cui si è staccata.',
  'brace-c9': 'Le sue cicatrici formano una mappa: porta al punto in cui il Primo Fuoco fu acceso.',
  'brace-c10': 'Non è mai stata viva: è il fumo della prima Guardia di Cenere, che non ha mai smesso di fare la guardia.',
  'brace-u5': 'Ha dimenticato il proprio nome: risponde solo al crepitio del fuoco.',
  'brace-u6': "Si accende da sola da cent'anni. Nessuno ha il coraggio di chiedersi chi la alimenti.",
  'brace-u7': 'Porta al collo un frammento di ogni presagio sotto cui ha combattuto: sette in tutto.',
  'brace-r4': "Il Drago di Brace era l'uovo che la Madre della Fornace covava quando fu tradita.",
  'brace-r5': 'Ogni eruzione del Monte arriva sempre un giorno dopo una bugia detta dentro la Cattedrale.',
  'brace-r6': "L'Araldo è l'unico a sapere chi era la Scintilla Errante prima di fuggire.",
  'brace-l2': 'Surtr non vuole distruggere il mondo: vuole scaldarlo prima che Nyxa lo raffreddi per sempre.',
  'brace-l3': "Dentro la Fornace Eterna c'è una sola brace: quella che il ladro senza nome non riuscì a rubare.",
  'marea-c7': 'Ogni onda anomala è un sospiro di Thalassa che ricorda Atlantide.',
  'marea-c8': 'La sua corazza è fatta con i frammenti delle mura di Atlantide.',
  'marea-c9': "Tra le perle che ha raccolto, una contiene un grido. Non l'ha mai aperta.",
  'marea-c10': 'La nebbia salmastra è il fiato delle Nereidi che dormono sotto le secche.',
  'marea-u5': "Il Tritone conosce un passaggio sotto la Cattedrale. Non l'ha detto neanche all'Ammiraglio.",
  'marea-u6': "Era l'ancora della nave dell'Ammiraglio. Si è spezzata il giorno in cui lui ha deciso di non tornare.",
  'marea-u7': 'Le correnti le hanno rivelato la fine di ogni Sigillo. Non ne ha mai parlato.',
  'marea-r4': 'Il Kraken sogna Atlantide. Se smettesse di sognare, la città sparirebbe davvero.',
  'marea-r5': 'È la stessa marea che salvò la Veggente la notte in cui nessuno le credette.',
  'marea-r6': 'Era una naufraga. Le secche la adottarono quando nessun altro la cercava.',
  'marea-l2': 'Scilla era una ninfa. Una gelosia la trasformò, e ogni nave che distrugge è un modo per non ricordarlo.',
  'marea-l3': 'La sua luce non illumina il mare: illumina il futuro, un giorno alla volta.',
  'radice-c7': 'Il muschio ricorda ogni piede che lo ha calpestato.',
  'radice-c8': 'Ogni Seme Errante è caduto dal Seme del Mondo. Nessuno sa quanti ne restino.',
  'radice-c9': 'È figlio della Lupa Grigia. La madre lo segue da lontano, senza farsi vedere.',
  'radice-c10': 'Una delle sue erbe cresce solo dove un Sigillo si è rotto. Ne ha trovate già troppe.',
  'radice-u5': 'Il Treant era il primo albero piantato dal Druida di Muschio, secoli fa.',
  'radice-u6': 'Al centro del cerchio dorme una fata che aspetta la fine dei Sigilli per svegliarsi.',
  'radice-u7': 'Il Cinghiale Furioso è il fratello maggiore del Cinghiale di Rovo, rimasto a difendere il bosco.',
  'radice-r4': 'La Driade Antica ha visto piantare il primo Sigillo. Non ha mai approvato.',
  'radice-r5': 'Il corno fu intagliato da una radice di Yggrin. Suona da solo quando la foresta è in pericolo.',
  'radice-r6': 'Porta tra le corna il primo germoglio di Yggrin, e lo protegge a ogni battaglia.',
  'radice-l2': 'Il Titano non combatte per la Rosa: combatte perché qualcuno ha tagliato il suo più giovane germoglio.',
  'radice-l3': "La Primavera Eterna è già esistita una volta, prima che Nyxa conoscesse l'inverno.",
  'vuoto-c7': 'Il suo velo è cucito con i fili del Velo che separa la Rosa dal Vuoto.',
  'vuoto-c8': 'Ogni tributo viene annotato dallo Scriba del Nulla. Il libro non ha ancora una fine.',
  'vuoto-c9': "È l'unico scheletro che ricorda il proprio nome. Lo ripete a ogni ritorno.",
  'vuoto-c10': 'Chi parla nel pozzo riceve risposta. Chi ascolta troppo, finisce per restarci.',
  'vuoto-u5': 'Il Negromante cerca un solo morto, tra tutti: la sorella che il Vuoto gli ha preso.',
  'vuoto-u6': 'Uno dei frammenti nel reliquiario appartiene a Nyxa. Nessuno sa come sia arrivato lì.',
  'vuoto-u7': 'Prega per la fine dei Sigilli, ma spera di sbagliarsi.',
  'vuoto-r4': 'Il Divoratore ha mangiato anche la propria anima, per fame. Da allora non si ferma più.',
  'vuoto-r5': "Il Patto delle Ombre ha una clausola nascosta. Chi l'ha letta non ha più firmato nulla.",
  'vuoto-r6': "L'Arcivescovo non crede nel Vuoto. Crede solo che i suoi fedeli meritino una seconda possibilità.",
  'vuoto-l2': 'Hel è figlia di Loki. Nella Rosa, è sorella della Scintilla Errante.',
  'vuoto-l3': 'Il Grande Patto è stato firmato da Nyxa con il sangue del primo Sigillo.',
  'tok-germoglio': 'Ogni Germoglio che cresce fino in fondo diventa, un giorno, un Druida di Muschio.',
  'tok-cucciolo': 'I cuccioli dell\'Orsa Madre non crescono mai: restano cuccioli finché le stelle esistono.',
};
export const CODEX_LEVEL = 2;
